### ISSUE TITLE
the npmjs package of openbridge-webcomponents-vue is empty

### ISSUE THREAD

**Issue by zhenhaisjtu** [Ocean-Industries-Concept-Lab/openbridge-webcomponents-legacy#148]
upgrade from 0.0.9 to 0.0.10, the openbridge-webcomponents-vue npmjs package is empty. try to build from src, it worked but an additional 'tslib' dep is required.

**Comment by tibnor** [comment]
Thanks for letting me know. I have now made a new release 0.0.12
