### ISSUE TITLE
Richbutton info parameter not connected in react library

### ISSUE THREAD

**Issue by OlaHyke** [Ocean-Industries-Concept-Lab/openbridge-webcomponents-legacy#149]
Hi, 
Expected results:
Setting info parameter to 'true' for RichButton object will disable mouse over effect

Actual result:
Setting info parameter to 'true' for RichButton object does not disable mouse over effect

**Comment by tibnor** [comment]
Hi @OlaHyke 

I'm not sure if I understand you correctly. What do you mean by "mouse over effect"? Are you thinking of styling or event handler? 

I tried this:

```
      <ObcRichButton size="single-line" info>
        <div slot="label">React Demo</div>
      </ObcRichButton>
```

That make it show in info-mode. (Alternatively use `info={true}`.) The cursor is in default mode. But the event handler is still triggered on clicks. 

Can you make a minimal example for me to test?

**Comment by OlaHyke** [comment]
Hi @tibnor , I was expecting the background color of the element to be static when info is enabled. But on my side it still changes color when I hover the mouse over it:
![image](https://github.com/Ocean-Industries-Concept-Lab/openbridge-webcomponents/assets/159035057/fe1fe0e6-63f2-4f2c-b5f8-110428ff9cd9)
edit: seems like the gif animation isnt loading but it would have shown that the background color of the element becomes brighter when the mouse is over the element

**Comment by tibnor** [comment]
I think this issue is solved. If not, contact me on slack :-)
