### ISSUE TITLE
no demo for valve / tanks 

### ISSUE THREAD

**Issue by enginyilmaaz** [Ocean-Industries-Concept-Lab/openbridge-webcomponents-legacy#212]
It is not clear how the connection between the tank  and the valves will be made. How are connection pipes created for valves? And there is no demo, there are only png images on the website and there is not enough information.

**Comment by tibnor** [comment]
Hi @enginyilmaaz! Thanks for the issue and sorry for the late response!

A demo of the valves and tanks are available here: https://openbridge-demo.web.app/ias. Here is the source code for that example: https://github.com/Ocean-Industries-Concept-Lab/openbridge-webcomponents/blob/main/packages/vue-demo/src/views/IasView.vue

You can also look on the storybook example for the pipes: https://openbridge-storybook.web.app/?path=/docs/line-example--docs
