### ISSUE TITLE
Emergency alarm

### ISSUE THREAD

**Issue by rafalwrzeszcz** [Ocean-Industries-Concept-Lab/openbridge-webcomponents-legacy#245]
We have encountered limitation when working with OpenBridge. Apart from non-alarming states there are three levels of alarms available: `Alarm`, `Warning` and `Caution`. However in reulatory specifications we have four levels with highest one being specified as:

```
Emergency alarm (highest priority), indicates that immediate danger to human life or to the ship
and its machinery exists and that immediate action must to be taken by the bridge team.
```

In our current implementation we represent it with same color as alarm but with different icon (`bullhorn`).

**Comment by tibnor** [comment]
Hi @rafalwrzeszcz! Thanks for the issue and sorry for the late response!

I think this is easier to discuss on Slack. Could you make a post there: https://join.slack.com/t/openbridgegroup/shared_invite/zt-2e4clvl6s-uZLkN5L3g8O~c1UZCN1reQ
