### ISSUE TITLE
Dev container postCreateCommand - build issue for vue wrapper

### ISSUE THREAD

**Issue by heathhenley** [Ocean-Industries-Concept-Lab/openbridge-webcomponents-legacy#253]
After adding #252 so that build:lib runs in the dev container, I'm seeing this error building the vue wrapper:

```
> @oicl/openbridge-webcomponents-vue@0.0.15 build
> npm run build:declarations && vite build


> @oicl/openbridge-webcomponents-vue@0.0.15 build:declarations
> vue-tsc --declaration --emitDeclarationOnly && node ./scripts/rename.js


/workspaces/openbridge-webcomponents/node_modules/vue-tsc/bin/vue-tsc.js:68
                        throw err;
                        ^
Search string not found: "for (const existingRoot of buildInfoVersionMap.roots) {"
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v20.15.0
npm error Lifecycle script `build:declarations` failed with error:
npm error Error: command failed
npm error   in workspace: @oicl/openbridge-webcomponents-vue@0.0.15
npm error   at location: /workspaces/openbridge-webcomponents/packages/openbridge-webcompo
nents-vue
npm error Lifecycle script `build` failed with error:
npm error Error: command failed
npm error   in workspace: @oicl/openbridge-webcomponents-vue@0.0.15
npm error   at location: /workspaces/openbridge-webcomponents/packages/openbridge-webcompo
nents-vue
```

Running `npm install` and then `npm run build:lib` in the root of the dir without the dev container I'm getting the same thing. This issue suggest that it's related to vue-tsc v1 vs vue-tsc v2 (https://github.com/vuejs/language-tools/issues/4484#issuecomment-2182469459) and updating from typescript 5.4 vs 5.5, 

The simplest repro is probably `npm i && npx vue-tsc` in the root of the project. I tried limiting the typescript version to 5.4.x in the root package.json as a test. This seems to work in the dev container and vue-tsc runs this time.

**Comment by tibnor** [comment]
Hi @heathhenley! Thanks for the issue and sorry for the late response.

This has been fixed in an earlier PR. But please reopen this if it is still not fixed!
