### ISSUE TITLE
Visualization of non existing value

### ISSUE THREAD

**Issue by thopil** [Ocean-Industries-Concept-Lab/openbridge-webcomponents-legacy#327]
E.g. I implemented the instrument field to visualize specific setpoint and current value data. In my case it can happen that the value is not set (null or undefined), but the component is always expecting a number. What should be the preferred solution to display a not set value?

**Comment by tibnor** [comment]
@thopil thanks for the question and sorry for the late response! I'm not sure what you would like to do. Do you want to show a setpoint value but not the current value as it is not defined? This is not covered by the design. So I need to discuss it with the designers. The best way to discuss this is to do it in slack: https://join.slack.com/t/openbridgegroup/shared_invite/zt-2e4clvl6s-uZLkN5L3g8O~c1UZCN1reQ

I'll close this issue. Make a post on slack if you would like to discuss this more :-)
