### ISSUE TITLE
Attribute "fractionDigits" of <obc-instrument-field> doesn't works

### ISSUE THREAD

**Issue by flo-ric** [Ocean-Industries-Concept-Lab/openbridge-webcomponents-legacy#417]
When I'm trying to use _fractionDigits_, nothing happens. An example below : 

```
<div class="instrument-container" style="width: 20vw; height: 20vw">
    <obc-instrument-field  fractionDigits="2" value="3.1" tag="Knots"></obc-instrument-field>
</div>

```
display : 

![image](https://github.com/user-attachments/assets/7c7a1724-5210-4026-806d-04f5b6de7af9)

**Comment by tibnor** [comment]
Hi @flo-ric!

I guess you are using the default 0.0.15 version. This does not include the fractionDigits update. Please update to the latest dev version 0.0.15-dev-20241127183633.

**Comment by flo-ric** [comment]
Thanks for the reply, but issue still here with 0.0.15-dev-20241127183633

**Comment by tibnor** [comment]
That is strange. It seems to work in storybook: https://openbridge-storybook.web.app/?path=/story/instrument-field--with-decimals

I think there is a issue with the version numbering if you set the version to _^_0.0.15-dev-20241127183633 it still uses 0.0.15. So I'm considering switching to just using the timestamp as the minor version number.

**Comment by flo-ric** [comment]
I update my response, It works fine on Chrome but not on Firefox, see below :
Chrome : 
![image](https://github.com/user-attachments/assets/fb8965d8-b26e-4979-8103-6ab7f1dca632)
FF :
![image](https://github.com/user-attachments/assets/4f88c2b9-eb95-4f64-89cf-c327490414c7)

Edit : Same issue on Chromium

**Comment by flo-ric** [comment]
I re-install 0.0.15-dev-20241127183633, and it's works now.
Thanks !
