### ISSUE TITLE
How to use this with vanilla javascript (without build tools)

### ISSUE THREAD

**Issue by Kylja** [Ocean-Industries-Concept-Lab/openbridge-webcomponents-legacy#73]
We have an HMI tool which supports only javascript. (the web server runs on a PLC)

I try to use the azimuth-thruster

In azimuth-thruster.js loading lit can be done with:
`import { unsafeCSS, LitElement, svg }  from "/lit/lit-all.min.js";`

but how to load the decorators? this does not work:
`import { property, customElement } from "/lit/lit-all.min.js";`   (both are unknown)

**Comment by tibnor** [comment]
Hi!

Thanks for the question :-)

Normally you don't use the components directly on such tools. To use the library on a system that only supports javascript you typically compile the typescript files to javascript. You could test this by building the vue or react demo and then copy that into the PLC.

**Comment by nimrof** [comment]
@tibnor 
Just a follow up, would you accept pull request that does the building on github so you could add a compiled bundle as asset when you do release?
